// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	ID          int32              `json:"id"`
	UserID      int32              `json:"userId"`
	OriginalUrl string             `json:"originalUrl"`
	ShortUrl    pgtype.Text        `json:"shortUrl"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
}

type User struct {
	ID        int32              `json:"id"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	Username  string             `json:"username"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}
