name: ci-test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    # setup postgress and redis services
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: url-shortener
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/
          which migrate

      - name: Run migrations
        run: make migrateup

      - name: Create .env file
        run: touch .env

      - name: Test
        run: make test
        env:
          APP_ADDRESS: ${{ vars.APP_ADDRESS }}
          APP_PORT: ${{ vars.APP_PORT }}
          DB_DRIVER: ${{ vars.DB_DRIVER }}
          REDIS_ADDRESS: ${{ vars.REDIS_ADDRESS }}
          REDIS_PORT: ${{ vars.REDIS_PORT }}
          REDIS_PASSWORD: ${{ vars.REDIS_PASSWORD }}
          REDIS_DB: ${{ vars.REDIS_DB }}
          DB_SOURCE: ${{ secrets.DB_SOURCE }}
